---
  - name: Add telegraf repo keys
    apt_key:
      url: "https://repos.influxdata.com/influxdb.key"
      state: present
    become: yes
    
  - name: "Debian | Add Telegraf repository"
    apt_repository:
      repo: "deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
      filename: "telegraf"
      state: present
    become: yes

  - name: Update package list
    apt: update_cache=yes
    register: apt_result
    become: true

  - name: Upgrade APT to the latest packages
    apt: upgrade=dist
    register: apt_result
    become: true

  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    become: true

  - name: Install common packages
    apt:
      name: [
        'git', 'python', 'python3', 'python-pip', 'python3-pip', 'nfs-common', 
        'net-tools', 'htop', 'apt-transport-https', 'ca-certificates', 
        'software-properties-common', 'curl', 'grep', 'unzip', 'zip', 
        'nano', 'grep', 'tree', 'ntp', 'ntpstat', 'ntpdate', 'telegraf'
        ]
      update_cache: yes
      cache_valid_time: 86400
      state: latest
    become: true

  - name: Autoremove unused packages
    apt: autoremove=yes
    changed_when: "'packages will be REMOVED' in apt_result.stdout"      
    become: true

  - name: Copy telegraf.conf
    copy:
      src: telegraf_pi.conf
      dest: /etc/telegraf/telegraf.conf
      owner: root
      group: root
      mode: 0644
    notify: "Restart Telegraf"
    become: yes

  - name: Restart telegraf
    service:
      name: telegraf
      state: restarted
      enabled: yes
    notify: "Restart Telegraf"
    become: yes
